### ISSUE TITLE
Doesn't compile on Linux with Swift 5.1

### ISSUE THREAD

**Issue by Fryie** [realm/SwiftLint#2874]
### New Issue Checklist

- [ x ] Updated SwiftLint to the latest version
- [ x ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The reason is that [the XML support has been moved to a separate package on Linux](https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/ReleaseNotes_Swift5.md), which breaks something in the transitive dependency SWXMLHash, where [the issue has apparently been fixed](https://github.com/drmohundro/SWXMLHash/pull/216), but of course this package is still using an old version.

Since the package is not a direct dependency of SwiftLint, it probably needs to be fixed in some other package first, but I have no idea how to find out which dependency pulls this in, so apologies for filing this here.

**Comment by Fryie** [comment]
I looked at it in a bit more detail. The dependency is pulled in by SourceKitten, which [has been updated](https://github.com/jpsim/SourceKitten/releases/tag/0.26.0) such that it also fetches the fixed version of SWXMLHash. However, the SourceKitten update also introduces new enum cases for some of its types, which means that the relevant places in the SwiftLint source that use those enums need to be updated in order for this to compile.

**Comment by minuscorp** [comment]
I experience this same issue on macOS compiling Swiftlint from scratch

**Comment by minuscorp** [comment]
In macOS this issue was fixed using SourceKitten at `0.25.0`

**Comment by Fryie** [comment]
Now it fails with a different error (repeated a couple of times):
```
/SwiftLint/Source/SwiftLintFramework/Models/Command.swift:83:59: error: 'scanUpToString' is unavailable
        guard let actionString = actionAndModifierScanner.scanUpToString(":"),
                                                          ^~~~~~~~~~~~~~
Foundation.Scanner:19:17: note: 'scanUpToString' was introduced in Swift 5.0
    public func scanUpToString(_ substring: String) -> String?
```

**Comment by minuscorp** [comment]
Have you tried to fix the version of SourceKitten to `0.25.0`?

**Comment by marcelofabri** [comment]
This is still an issue even with SourceKitten 0.26.0. See #2896.

I will try to take a look later today.

**Comment by Fryie** [comment]
@marcelofabri #2896 appears to fix the issue for me

**Comment by marcelofabri** [comment]
Thanks for verifying, @Fryie 🚀
